background:
  background_dir: null
  color: null
  enabled: false
  random_crop: true
character:
  font: FONT_HERSHEY_SCRIPT_COMPLEX
  height: 64
  thickness: 2
  width: 64
color:
  color_range_b:
  - 0
  - 255
  color_range_g:
  - 0
  - 255
  color_range_r:
  - 0
  - 255
  fixed_color: null
  random_color: false
dataset:
  dataset_dir: C:/Users/Viper/Desktop/text_baker/.textbaker/custom_characters
  extensions:
  - .png
  - .jpg
  - .jpeg
  - .bmp
  recursive: true
output:
  create_labels: true
  format: png
  label_format: txt
  output_dir: output
  quality: 95
seed: 42
spacing: 0
text_length:
- 1
- 10
texture:
  enabled: false
  opacity: 1.0
  per_character: false
  texture_dir: null
transform:
  perspective_range:
  - 0.0
  - 0.0
  rotation_range:
  - 0.0
  - 0.0
  scale_range:
  - 0.9
  - 1.1
  shear_range:
  - 0.0
  - 0.0
